services:
  
  backendcam:
    container_name: backendcam
    build:
      context: ./main-gateway
      dockerfile: Dockerfile
    image: backendcam:latest
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Bangkok"
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/serviceAccount.json"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      FIREBASE_CREDENTIALS_PATH: "file:/secrets/serviceAccount.json"
      JAVA_OPTS: >-
        -Xms2G -Xmx2G
        -XX:MaxDirectMemorySize=3G
        -XX:MaxMetaspaceSize=256M
        -Xss512k
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
    volumes:
      - ./main-gateway/hls:/hls
      - ./main-gateway/secrets/serviceAccount.json:/secrets/serviceAccount.json:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/timezone:ro
    restart: unless-stopped
    # network_mode: host
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 2G

  motion-detect:
    container_name: motion-detect
    build:
      context: ./motion-detect
      dockerfile: Dockerfile
    image: motion-detect:latest
    ports:
      - "8082:8082"
    environment:
      TZ: "Asia/Bangkok"
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/serviceAccount.json"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      FIREBASE_CREDENTIALS_PATH: "file:/secrets/serviceAccount.json"
      JAVA_OPTS: "-Xmx4g -Xms2g -XX:MaxDirectMemorySize=2g"
    volumes:
      - ./motion-detect/secrets/serviceAccount.json:/secrets/serviceAccount.json:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/timezone:ro
    depends_on:
      - kafka
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 8G
        reservations:
          cpus: '4'
          memory: 4G


  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "19092:19092" # external listener
      - "9093:9093"   # controller listener
    environment:
      # KRaft settings (broker + controller in one) development mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # controller quorum config (just one node)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: "yes"

      # Only in development/testing environments
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  license-plate-detector:
    build:
      context: ./license-plate-v1s-main
      dockerfile: Dockerfile
    container_name: license-plate-detector
    ports:
      - "8000:8000"
    volumes:
      - ./license-plate-v1s-main/input:/app/input
      - ./license-plate-v1s-main/output:/app/output
      - ./license-plate-v1s-main/models:/app/models
      - ./license-plate-v1s-main/.env.dev:/app/.env
      - ./license-plate-v1s-main/secrets:/secrets
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=motion-event
      - KAFKA_GROUP_ID=license-plate-consumer-group
    depends_on:
      - kafka
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  flutter-web:
    build:
      context: ./flutter_cctv-main
      dockerfile: Dockerfile
    container_name: flutter-web
    volumes:
      - /var/www/flutter:/output
    environment:
      TZ: "Asia/Bangkok"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  accident-detector:
    build:
      context: ./accident-ai-main
      dockerfile: Dockerfile
    container_name: accident-detector
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=motion-event
      - KAFKA_GROUP_ID=accident-consumer-group
      - KAFKA_AUTO_OFFSET_RESET=earliest
    volumes:
      - ./accident-ai-main/output:/output
      - ./accident-ai-main/.env:/app/.env
      - ./accident-ai-main/secrets:/secrets
    depends_on:
      - kafka
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 3G

  camera-status-checker:
    container_name: camera-status-checker
    build:
      context: ./camera-status-checker
      dockerfile: Dockerfile
    image: camera-status-checker:latest
    ports:
      - "8081:8081"
    environment:
      TZ: "Asia/Bangkok"
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/serviceAccount.json"
      FIREBASE_CREDENTIALS_PATH: "file:/secrets/serviceAccount.json"
    volumes:
      - ./camera-status-checker/secrets/serviceAccount.json:/secrets/serviceAccount.json:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/timezone:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3003:3001"
    volumes:
      - ./uptime-kuma-data:/app/data
    environment:
      - TZ=Asia/Bangkok
      - UMASK=0022
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"